/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Windows 11
 */
public class VistaCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCalculadora.class.getName());

    /**
     * Creates new form VistaCalculadora
     */
    public VistaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPantalla = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnRaizCuadrada = new javax.swing.JButton();
        btnRaizCubica = new javax.swing.JButton();
        btnLogaritmo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPantalla.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPantalla.setText("0");
        getContentPane().add(txtPantalla, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 5, 5));

        btn7.setText("7");
        jPanel2.add(btn7);

        btn8.setText("8");
        jPanel2.add(btn8);

        btn9.setText("9");
        jPanel2.add(btn9);

        btnDividir.setText("÷");
        jPanel2.add(btnDividir);

        btn4.setText("4");
        jPanel2.add(btn4);

        btn5.setText("5");
        jPanel2.add(btn5);

        btn6.setText("6");
        jPanel2.add(btn6);

        btnMultiplicar.setText("×");
        jPanel2.add(btnMultiplicar);

        btn1.setText("1");
        jPanel2.add(btn1);

        btn2.setText("2");
        jPanel2.add(btn2);

        btn3.setText("3");
        jPanel2.add(btn3);

        btnRestar.setText("-");
        jPanel2.add(btnRestar);

        btn0.setText("0");
        jPanel2.add(btn0);

        btnPunto.setText(".");
        jPanel2.add(btnPunto);

        btnIgual.setText("=");
        jPanel2.add(btnIgual);

        btnSumar.setText("+");
        jPanel2.add(btnSumar);

        btnRaizCuadrada.setText("√");
        jPanel2.add(btnRaizCuadrada);

        btnRaizCubica.setText("∛");
        jPanel2.add(btnRaizCubica);

        btnLogaritmo.setText("ln");
        jPanel2.add(btnLogaritmo);

        btnLimpiar.setText("C");
        jPanel2.add(btnLimpiar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLogaritmo;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaizCuadrada;
    private javax.swing.JButton btnRaizCubica;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
